### ISSUE TITLE
Only repeating due soon tasks are being added

### ISSUE THREAD

**Issue by aw237** [wxxedu/OmniFocus-Today#1]
Hi,

Thank you for sharing this useful plugin!

There's one issue I noticed: Due soon tasks are only being added to the Today perspective upon adding numbering, if they are repeating tasks. 

Thanks again.
Adrian

**Comment by wxxedu** [comment]
Hi! I'll have a look at it over the weekend. Thanks!

**Comment by wxxedu** [comment]
Hey, I think it's fixed now. You can download it via the releases tab. :-)

**Comment by aw237** [comment]
Thank you @wxxedu, I just tested it and can confirm.

In case you plan to further develop this plugin in the future, I wanted to share an idea: 

A useful addition might be to exclude items from being shown in the Today view if they have a certain user-defined tag, even if they also have a Due Soon date. In my case, there's a category of tasks with due dates ("Reminders") that I would ideally want to exclude from the Today view.

Have a nice day.
